version = "3.8.3"

runner.dialect = scala3

maxColumn = 120
indent.main = 2
indent.significant = 2
indent.callSite = 2
indent.ctrlSite = 2
indent.defnSite = 2
indent.ctorSite = 2
indent.caseSite = 5
indent.extendSite = 4

align.preset = none

newlines.topLevelStatements = [before]
newlines.implicitParamListModifierPrefer = before
newlines.afterCurlyLambdaParams = preserve
newlines.beforeMultiline = keep

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors
]

rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.generalExpressions = false

rewrite.sortModifiers.order = [
  "override", "private", "protected", "implicit", "final", "sealed", "abstract", "lazy"
]

spaces.inImportCurlyBraces = false
spaces.beforeContextBoundColon = Never

importSelectors = singleLine

optIn.configStyleArguments = true
optIn.breaksInsideChains = false

danglingParentheses.preset = false
danglingParentheses.defnSite = false
danglingParentheses.callSite = false
danglingParentheses.ctrlSite = false

verticalMultiline.atDefnSite = false
verticalMultiline.arityThreshold = 4
verticalMultiline.newlineAfterOpenParen = true

trailingCommas = preserve

docstrings.style = Asterisk
docstrings.wrap = no

project.git = true
