version = "3.8.3"

runner.dialect = scala3

maxColumn = 100
indent.main = 2
indent.significant = 2
indent.callSite = 2
indent.ctrlSite = 2
indent.defnSite = 2
indent.ctorSite = 2
indent.caseSite = 5
indent.extendSite = 4

align.preset = more
align.multiline = true
align.arrowEnumeratorGenerator = true
align.openParenCallSite = false
align.openParenDefnSite = false

newlines.topLevelStatements = [before, after]
newlines.implicitParamListModifierPrefer = before
newlines.afterCurlyLambdaParams = preserve

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors
]

rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.generalExpressions = false

rewrite.sortModifiers.order = [
  "override", "private", "protected", "implicit", "final", "sealed", "abstract", "lazy"
]

spaces.inImportCurlyBraces = false
spaces.beforeContextBoundColon = Never

importSelectors = singleLine

optIn.configStyleArguments = true
optIn.breaksInsideChains = false

danglingParentheses.preset = true
danglingParentheses.defnSite = true
danglingParentheses.callSite = true
danglingParentheses.ctrlSite = true

verticalMultiline.atDefnSite = false
verticalMultiline.arityThreshold = 4
verticalMultiline.newlineAfterOpenParen = true

trailingCommas = preserve

docstrings.style = Asterisk
docstrings.wrap = no

project.git = true
